id: I65ED66C6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-02-02T10:10:27+00:00'
last_modified: '2022-06-16T05:05:33.690688+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14303
  title: གསུང་འབུམ། ཆོས་ཀྱི་བློ་གྲོས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A90A:
      image_group_id: I1KG15193
      title: ''
      total_pages: 362
      order: 1
      base_file: A90A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
