id: P000794
initial_creation_type: ocr
created_at: 2/02/2021
last_modified_at: 2021-12-17 10:11:01.400349
source_metadata:
  id: bdr:W1KG14303
  title: གསུང་འབུམ། ཆོས་ཀྱི་བློ་གྲོས།
  volumes:
    fc811bd9fbf949c3963c2369bfec887f:
      image_group_id: I1KG15193
      title: ''
      volume_number: 1
      total_pages: 362
      base_file: v001.txt
    a7040735371f4219ac12c24dfc84b1eb:
      image_group_id: I1KG15194
      title: ''
      volume_number: 2
      total_pages: 328
      base_file: v002.txt
    16cceae513404681a1895b7af94a8b65:
      image_group_id: I1KG15195
      title: ''
      volume_number: 3
      total_pages: 328
      base_file: v003.txt
    1b527b8a21fa4d389087f854e048d726:
      image_group_id: I1KG15196
      title: ''
      volume_number: 4
      total_pages: 336
      base_file: v004.txt
    f0415450435849929c98799e64c159ab:
      image_group_id: I1KG15197
      title: ''
      volume_number: 5
      total_pages: 360
      base_file: v005.txt
    7345d9a26b7e4ff6b491c6371fd9aebf:
      image_group_id: I1KG15198
      title: ''
      volume_number: 6
      total_pages: 305
      base_file: v006.txt
    70c2a9d195e945a49721d26c0e78870a:
      image_group_id: I1KG15199
      title: ''
      volume_number: 7
      total_pages: 317
      base_file: v007.txt
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
